// <auto-generated />
using System;
using GreatCurrency.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreatCurrency.DAL.Migrations
{
    [DbContext(typeof(GreatCurrencyContext))]
    [Migration("20250827092624_AddLegalEntitiesRates")]
    partial class AddLegalEntitiesRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreatCurrency.DAL.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bank", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.BankDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CityId");

                    b.ToTable("BankDepartment", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.BestCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<double>("EURBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("EURSaleRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBSaleRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<double>("USDBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("USDSaleRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CityId");

                    b.HasIndex("RequestId");

                    b.ToTable("BestCurrency", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.CSCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyServicesId")
                        .HasColumnType("integer");

                    b.Property<double>("EURBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("EURSaleRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBSaleRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<double>("USDBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("USDSaleRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyServicesId");

                    b.HasIndex("RequestId");

                    b.ToTable("CSCurrencies", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityURL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankDepartmentId")
                        .HasColumnType("integer");

                    b.Property<double>("EURBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("EURSaleRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBSaleRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<double>("USDBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("USDSaleRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BankDepartmentId");

                    b.HasIndex("RequestId");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.CurrencyService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrencyServices", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.LECurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<double>("CNYBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("CNYSaleRate")
                        .HasColumnType("double precision");

                    b.Property<double>("EURBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("EURSaleRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("RUBSaleRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<double>("USDBuyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("USDSaleRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("RequestId");

                    b.ToTable("LECurrencies", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.LERequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IncomingDate")
                        .HasColumnType("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("LERequests", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IncomingDate")
                        .HasColumnType("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.SCRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IncomingDate")
                        .HasColumnType("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("SCRequests", (string)null);
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.BankDepartment", b =>
                {
                    b.HasOne("GreatCurrency.DAL.Models.Bank", "Bank")
                        .WithMany("BankDepartments")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreatCurrency.DAL.Models.City", "City")
                        .WithMany("BankDepartments")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("City");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.BestCurrency", b =>
                {
                    b.HasOne("GreatCurrency.DAL.Models.Bank", "Bank")
                        .WithMany("BestCurrencies")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreatCurrency.DAL.Models.City", "City")
                        .WithMany("BestCurrencies")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreatCurrency.DAL.Models.Request", "Request")
                        .WithMany("BestCurrencies")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("City");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.CSCurrency", b =>
                {
                    b.HasOne("GreatCurrency.DAL.Models.CurrencyService", "CurrencyService")
                        .WithMany("CSCurrencies")
                        .HasForeignKey("CurrencyServicesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreatCurrency.DAL.Models.SCRequest", "SCRequest")
                        .WithMany("CSCurrencies")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrencyService");

                    b.Navigation("SCRequest");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.Currency", b =>
                {
                    b.HasOne("GreatCurrency.DAL.Models.BankDepartment", "BankDepartment")
                        .WithMany("Currencies")
                        .HasForeignKey("BankDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreatCurrency.DAL.Models.Request", "Request")
                        .WithMany("Currencies")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankDepartment");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.LECurrency", b =>
                {
                    b.HasOne("GreatCurrency.DAL.Models.Bank", "Bank")
                        .WithMany("LECurrencies")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreatCurrency.DAL.Models.LERequest", "LERequest")
                        .WithMany("LECurrencies")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("LERequest");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.Bank", b =>
                {
                    b.Navigation("BankDepartments");

                    b.Navigation("BestCurrencies");

                    b.Navigation("LECurrencies");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.BankDepartment", b =>
                {
                    b.Navigation("Currencies");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.City", b =>
                {
                    b.Navigation("BankDepartments");

                    b.Navigation("BestCurrencies");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.CurrencyService", b =>
                {
                    b.Navigation("CSCurrencies");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.LERequest", b =>
                {
                    b.Navigation("LECurrencies");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.Request", b =>
                {
                    b.Navigation("BestCurrencies");

                    b.Navigation("Currencies");
                });

            modelBuilder.Entity("GreatCurrency.DAL.Models.SCRequest", b =>
                {
                    b.Navigation("CSCurrencies");
                });
#pragma warning restore 612, 618
        }
    }
}
